apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhooq-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jhooq-springboot
  template:
    metadata:
      labels:
        app: jhooq-springboot
    spec:
      containers:
        - name: springboot
          image: docker.io/7769068855/jhooq-docker-demo:jhooq-docker-demo

          resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "128Mi"
              cpu: "512m"

          ports:
            - containerPort: 8081

          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /hello
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

          env:
            - name: PORT
              value: "8080"
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: jhooq-springboot
#spec:
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: 8080
#  selector:
#    app: jhooq-springboot
---
apiVersion: v1
kind: Service
metadata:
  name: jhooq-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      name: http
    - port: 443
      targetPort: 8080
      nodePort: 30443
      name: https
  selector:
    app: jhooq-springboot

